nwpp_prototypes/nwpp_prototypes/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^questions/', include('questions.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

nwpp_prototypes/questions/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'questions'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^tags/$', views.tags, name='tags'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^signin_attempt/$', views.signin_attempt, name='signin_attempt'),
    url(r'^signout/$', views.signout, name='signout'),
    url(r'^question_detail/(?P<question_id>[0-9]+)$', views.question_detail, name='question_detail'),
    url(r'^edit_question/(?P<question_id>[0-9]+)$', views.edit_question, name='edit_question'),
    url(r'^save_question/(?P<question_id>[0-9]+)$', views.save_question, name='save_question'),
    url(r'^new_question/$', views.new_question, name='new_question'),
    url(r'^post_question/$', views.post_question, name='post_question'),
    url(r'^post_answer/$', views.post_answer, name='post_answer'),
    url(r'^register/$', views.register, name='register'),
    url(r'^activate/$', views.activate, name='activate'),
    url(r'^profile/(?P<user_id>[0-9]+)$', views.profile, name='profile'),
    url(r'^edit_profile/(?P<user_id>[0-9]+)$', views.edit_profile, name='edit_profile'),
    url(r'^search/$', views.search, name='search'),
    url(r'^solve/(?P<answer_id>[0-9]+)$', views.solve, name='solve'),
    url(r'^voteup/(?P<answer_id>[0-9]+)$', views.voteup, name='voteup'),
    url(r'^votedown/(?P<answer_id>[0-9]+)$', views.votedown, name='votedown'),
    url(r'^clear_all/$', views.clear_all, name='clear_all'),
    url(r'^flag/$', views.flag, name='flag'),
    url(r'^new_bookmark/$', views.new_bookmark, name='new_bookmark'),
    url(r'^delete_bookmark/$', views.delete_bookmark, name='delete_bookmark'),
    url(r'^bookmarks/(?P<user_id>[0-9]+)$', views.bookmarks, name='bookmarks'),
    url(r'^hive/(?P<hive_id>[0-9]+)$', views.hive, name='hive'),
    url(r'^new_hive/$', views.new_hive, name='new_hive'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nwpp_prototypes/questions/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField
from django.utils.html import escape


def truncate(value):
    summary_size = 20
    if len(value) > summary_size:
        return '{0}...'.format(value[:summary_size])
    else:
        return value


class Icon(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return f'<span class="fa fa-{self.name}"></span>'


class Category(models.Model):
    title = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title

    def icon(self):  # This is...clunky, and hard-coded (and thus limiting). But it works...
        if self.title == 'Fundamentals':
            return '<span class="fa fa-th-large"></span> FUNDAMENTALS | '
        elif self.title == 'Operations':
            return '<span class="fa fa-cog"></span> OPERATIONS | '
        elif self.title == 'Planning':
            return '<span class="fa fa-line-chart"></span> PLANNING | '


class Hive(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=200)
    icon = models.ForeignKey(Icon, null=True, on_delete=models.SET_NULL)
    description = models.TextField(null=True, blank=True)
    # colorField??

    class Meta:
        verbose_name = 'Hive'
        verbose_name_plural = 'Hives'
        ordering = ('-created',)

    def __str__(self):
        return self.title


class Invite(models.Model):
    hive = models.ForeignKey(Hive, null=True, on_delete=models.CASCADE)
    from_user = models.ForeignKey(User, related_name='+', on_delete=models.CASCADE)
    to_user = models.ForeignKey(User, on_delete=models.CASCADE)
    pass


class Question(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL)
    hive = models.ForeignKey(Hive, null=True, blank=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=200)
    body = RichTextField()
    tags = TaggableManager()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    solved = models.BooleanField(default=False)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def bookmark_check(self, user):
        bookmark_ids = []
        for bookmark in user.bookmark_set.all():
            bookmark_ids.append(bookmark.question.id)
        # print(bookmark_ids)
        # print(self.id)
        return self.id in bookmark_ids


class Answer(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    body = RichTextField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    solution = models.BooleanField(default=False)
    vote_counter = models.IntegerField(default=0)

    def __str__(self):
        return f'RE: {self.question.title}'

    def voters(self):
        voters = []
        for vote in self.vote_set.all():
            voters.append(vote.user)
        return voters

    def flaggers(self):
        flaggers = []
        for flag in self.flag_set.all():
            flaggers.append(flag.user)
        return flaggers


class Comment(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    body = RichTextField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'
        ordering = ('-created',)

    def __str__(self):
        return f'Comment by {self.user.username} on {self.created} {self.answer}'


class Profile(models.Model):  # Extends base User class with additional fields
    user = models.OneToOneField(User, primary_key=True, related_name='profile', on_delete=models.CASCADE)
    hives = models.ManyToManyField(Hive, blank=True)
    avatar = models.ImageField(upload_to="media/", blank=True, null=True)
    questions = models.IntegerField(default=0)
    answers = models.IntegerField(default=0)
    comments = models.IntegerField(default=0)
    solutions = models.IntegerField(default=0)
    vote_counter = models.IntegerField(default=0)
    flags = models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    searches = models.IntegerField(default=0)
    edits = models.IntegerField(default=0)
    bookmarks = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.user.username} - Profile'

    def earned_badges(self):
        badges = []
        for badge in self.user.badge_set.all():
            badges.append(badge)
        return badges


class Vote(models.Model):
    up = 'u'
    down = 'd'
    vote_types = (
        (up, 'Up voted'),
        (down, 'Down voted'),
    )

    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    vote_type = models.CharField(max_length=1, choices=vote_types)

    class Meta:
        verbose_name = 'Vote'
        verbose_name_plural = 'Votes'
        ordering = ('-date',)

    def __str__(self):
        if self.vote_type == self.up:
            return f'{self.user.username} voted up {self.answer}'
        else:
            return f'{self.user.username} voted down {self.answer}'


class Flag(models.Model):
    q = 'q'
    a = 'a'
    c = 'c'
    flag_types = (
        (q, 'Question'),
        (a, 'Answer'),
        (c, 'Comment'),
    )

    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    flag_type = models.CharField(max_length=1, choices=flag_types)
    date = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey(Question, null=True, blank=True)
    answer = models.ForeignKey(Answer, null=True, blank=True)
    comment = models.ForeignKey(Comment, null=True, blank=True)
    reason = models.CharField(max_length=200)
    # reason options are defined through a <select> tag on the front end in question_detail.html
    body = models.TextField()

    class Meta:
        verbose_name = 'Flag'
        verbose_name_plural = 'Flags'
        ordering = ('-date',)

    def __str__(self):
        return truncate(self.body)


class Bookmark(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    date = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey(Question, null=True, blank=True)
    note = models.TextField(null=True, blank=True)  # 2018.01.04 - NYI, presently no way leaving a note on front end

    class Meta:
        verbose_name = 'Bookmark'
        verbose_name_plural = 'Bookmarks'
        ordering = ('-date',)

    def __str__(self):
        return f'{self.user.username} bookmarked Question {self.question.id}'


class Notification(models.Model):
    answered = 'a'
    solved = 's'
    voted = 'v'
    flagged = 'f'
    notification_types = (
        (answered, 'Answered'),
        (solved, 'Solved'),
        (voted, 'Voted'),
        (flagged, 'Flagged')
        )

    answered_template = '<div class="notification_message"><a href="/questions/profile/{0}">{1}</a> provided an answer to your question: <a href="/questions/question_detail/{2}">{3}</a></div>'
    solved_template = '<div class="notification_message"><a href="/questions/profile/{0}">{1}</a> accepted your answer to the question: <a href="/questions/question_detail/{2}">{3}</a></div>'
    voted_template = '<div class="notification_message"><a href="/questions/profile/{0}">{1}</a> voted for your answer to the question: <a href="/questions/question_detail/{2}">{3}</a></div>'
    flagged_template = '<div class="notification_message"><a href="/questions/question_detail/{0}">Your post</a> was flagged {1} for the following reason: <i>"{2}"</i></div>'

    from_user = models.ForeignKey(User, related_name='+', on_delete=models.CASCADE)
    to_user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)
    flag = models.ForeignKey(Flag, null=True, blank=True, on_delete=models.CASCADE)
    notification_type = models.CharField(max_length=1, choices=notification_types)

    class Meta:
        verbose_name = 'Notification'
        verbose_name_plural = 'Notifications'
        ordering = ('-date',)

    def __str__(self):
        if self.notification_type == self.answered:
            return self.answered_template.format(
                escape(self.from_user.pk),
                escape(self.from_user.username),
                self.question.pk,
                escape(truncate(self.question.title))
                )
        elif self.notification_type == self.solved:
            return self.solved_template.format(
                escape(self.from_user.pk),
                escape(self.from_user.username),
                self.answer.question.pk,
                escape(truncate(self.answer.question.title))
                )
        elif self.notification_type == self.voted:
            return self.voted_template.format(
                escape(self.from_user.pk),
                escape(self.from_user.username),
                self.answer.question.pk,
                escape(truncate(self.answer.question.title))
                )
        elif self.notification_type == self.flagged:

nwpp_prototypes/questions/forms.py
from django import forms
from django.forms import ModelForm
from ckeditor.widgets import CKEditorWidget
from .models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'category', 'body', 'tags']
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Title', 'class': 'form-control'}),
            # 'category': forms.Select(attrs={'placeholder': 'Category'}), # <-- This doesn't work...
            'tags': forms.TextInput(attrs={'placeholder': 'Tags, separated by commas', 'class': 'form-control'}),
            'body': forms.CharField(widget=CKEditorWidget)
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['body']

nwpp_prototypes/questions/templates/questions/index.html
{% extends 'questions/base.html' %}
{% load static %}

{% block heading %}

    <div class="row" id="heading">
        <div class="col">
            <span style="font-size: 2em" class="page_heading">Q&A</span>
        </div>
    </div>

{% endblock %}

{% block feature %}

    {% if not request.user.is_authenticated %}

        <br />
        <br />
        <br />
        <div class="container">
            <div class="row" id="how_it_works">

                <div class="col" id="onboard_hexes_all">
                    <div id="onboard_hex0" class="hexagon">
                        <span id="onboard_how" class="onboard-icon" style="font-size: 1em">HOW IT WORKS</span>
                        <div class="hexTop"></div>
                        <div class="hexBottom"></div>
                    </div>
                    <div id="onboard_hex1" class="hexagon dp_tooltip">
                        <span class="tooltip_large">Anyone can ask a question</span>
                        <span class="fa fa-comment-o onboard-icon" style="font-size: 4em"></span>
                        <div class="hexTop"></div>
                        <div class="hexBottom"></div>
                    </div>
                    <div id="onboard_hex2" class="hexagon dp_tooltip">
                        <span class="tooltip_large">Answers can be provided by others</span>
                        <span class="fa fa-comments-o onboard-icon" style="font-size: 4em"></span>
                        <div class="hexTop"></div>
                        <div class="hexBottom"></div>
                    </div>
                    <div id="onboard_hex3" class="hexagon dp_tooltip">
                        <span class="tooltip_large">Answers are voted on, and a solution is identified</span>
                        <span class="fa fa-check-circle-o onboard-icon" style="font-size: 4em"></span>
                        <div class="hexTop"></div>
                        <div class="hexBottom"></div>
                    </div>
                    <a href="{% url 'questions:register' %}">
                        <div id="onboard_hex4" class="hexagon">
                            <span id="onboard_sign" class="onboard-icon" style="font-size: 1em">SIGN UP</span>
                            <div class="hexTop"></div>
                            <div class="hexBottom"></div>
                        </div>
                    </a>
                </div>
            </div>
        </div>

    {% endif %}

    {% if request.user.is_authenticated %}

        <br />
        <div class="container">
            <div id="ask_question">
                <a href="{% url 'questions:new_question' %}" class="btn btn-outline-info btn-lg"><span class="fa fa-comment-o"></span> ASK A QUESTION</a>
            </div>
        </div>


    {% endif %}

{% endblock %}


{% block content %}

<br />
<div class="container" id="index_container">

            {% for question in questions %}
                <div id="question_wrapper">
                    <!--hex version-->
                    <a href="{% url 'questions:profile' question.user.id %}">
                        <div class="hexagonSmall" style="background-image: url('/{{ question.user.profile.avatar }}'">
                            <div class="hexTopSmall"></div>
                            <div class="hexBottomSmall"></div>
                        </div>
                    </a>
                    <!--<div>-->
                        <!--<a href="{% url 'questions:profile' question.user.id %}">-->
                            <!--<img src="/{{ question.user.profile.avatar }}" height="46" width="46" class="avatar_thumbnail"/>-->
                        <!--</a>-->
                    <!--</div>-->
                    <div id="question_container">
                        <div id="question_data">
                            {{ question.answer_set.count }} answers | {{ question.views }} views |
                            by <a href="{% url 'questions:profile' question.user.id %}"> {{ question.user }} </a> on <i>{{ question.created }}</i>
                        </div>
                        <div id="question_header">
                            <a href="{% url 'questions:question_detail' question.id %}" class="text_link">
                                <div><b>{{ question.title }}</b>
                                <br />
                                    <span style="opacity: .5">
                                        <span>
                                            {% autoescape off %} {{ question.category.icon }} {% endautoescape %}
                                        </span>
                                        <span>
                                            tags:
                                            {% for tag in question.tags.all %}
                                                {{ tag }}
                                            {% endfor %}
                                        </span>
                                    </span>
                                </div>
                            </a>
                        </div>

                        {% if question.solved == True %}
                            <div class="solved_indicator" id="solved">✓</div>
                        {% else %}
                            <div class="unsolved_indicator" id="unsolved">?</div>
                        {% endif %}

                    </div>
                </div>
            {% endfor %}

            <br />
                <div class="pagination">
                    <span class="step-links">
                        {% if questions.has_previous %}
                            <a href="?page={{ questions.previous_page_number }}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ questions.number }} of {{ questions.paginator.num_pages }}
                        </span>

                        {% if questions.has_next %}
                            <a href="?page={{ questions.next_page_number }}">next</a>
                        {% endif %}
                    </span>
                </div>

<br />
<br />

</div>

{% endblock %}

nwpp_prototypes/questions/templates/questions/question_detail.html
{% extends 'questions/base.html' %}

{% block heading %}

    <div class="row" id="heading">
        <div class="col-md-1 hidden-sm hidden-xs">
            <a href="{% url 'questions:profile' question.user.id %}">
                <div class="hexagonMedium" style="background-image: url('/{{ question.user.profile.avatar }}'">
                    <div class="hexTopMedium"></div>
                    <div class="hexBottomMedium"></div>
                </div>
            </a>
            <!--<a href="{% url 'questions:profile' question.user.id %}">-->
                <!--<img src="/{{ question.user.profile.avatar }}" height="60" width="60" class="avatar_thumbnail"/>-->
            <!--</a>-->
        </div>
        <div class="col-md-11 col-sm-12">
            <div class="page_heading" id="question_detail">{{ question.title }}</div>
        </div>

    </div>

{% endblock %}


{% block content %}

<!-- Flag Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">FLAG </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="exampleModalLongBody">
                <form action="{% url 'questions:flag' %}" method="post">
                    {% csrf_token %}
                    <!--The 2 values below are adjusted via JS when a flag is clicked -->
                    <input id="flag_type" type="hidden" value="PH1" name="object_type"/>
                    <input id="flag_type_id" type="hidden" value="PH2" name="object_id"/>

                    <p><select name="reason">
                        <option disabled>Choose a reason</option>
                        <option value="inappropriate">Inappropriate Content</option>
                        <option value="duplicate">Duplicate Question</option>
                        <option value="off-topic">Off-topic</option>
                    </select></p>
                    <p><textarea name="body" style="width: 100%" placeholder="You are not a beautiful and unique snowflake." required></textarea></p>
                    <button type="submit" class="btn btn-secondary">CONFIRM</button>
                </form>
            </div>
            <div class="modal-footer">
                <span class="fa fa-info-circle"></span><i>Flags from 3 unique users will lock content</i>
            </div>
        </div>
    </div>
</div>

<br />

<div class="container">
    <div class="row">
        <div class="col-lg-9">
            <!--<h4>{{ question.title }}</h4>-->
            <p>
                <span class="question_actions">
                    {% if bookmark %}
                        <a href="#"><span class="fa fa-bookmark" id="question_bookmark" style="font-size: 2em"></span></a>
                    {% else %}
                        <a href="#"><span class="fa fa-bookmark-o" id="question_bookmark" style="font-size: 2em"></span></a>
                    {% endif %}
                </span>
                by <a href="{% url 'questions:profile' question.user.id %}">{{ question.user }}</a>
                | published {{ question.created }}
                {% if request.user == question.user %}
                | <a href="{% url 'questions:edit_question' question.id %}">EDIT</a>
                {% endif %}
            </p>
            <p class="question_body">{{ question.body|safe }}</p>
            <p>CATEGORY - {{ question.category }}</p>
            <p> TAGS -
                {% for tag in tags %}
                    {{ tag }}
                {% endfor %}</p>
            <a href="#"><span class="fa fa-flag-o" id="question_flag" style="font-size: 1.5em" data-toggle="modal" data-target="#exampleModalLong"></span></a>


            {% if answers.count > 0 %}

                <hr >
                <h5>ANSWERS</h5>
                <ul>
                    {% for answer in answers %}

                        {% if answer.solution == True %}
                            <li class="solution_wrapper" style="list-style: none">
                        {% else %}
                            <li class="answer_wrapper" style="list-style: none">
                        {% endif %}
                        <div id="answer_avatar">
                            <a href="{% url 'questions:profile' answer.user.id %}">
                                <div class="hexagonSmall" style="background-image: url('/{{ answer.user.profile.avatar }}'">
                                    <div class="hexTopSmall"></div>
                                    <div class="hexBottomSmall"></div>
                                </div>
                            </a>
                            <!--<a href="{% url 'questions:profile' answer.user.id %}">-->
                                <!--<img src="/{{ answer.user.profile.avatar }}" height="46" width="46" class="avatar_thumbnail" id="heading_avatar"/>-->
                            <!--</a>-->
                        </div>
                            <div class="answer_data">
                                <div id="solution_indicator" class="dp_tooltip">
                                    {% if request.user == question.user and question.solved == False %}
                                        <span class="tooltip_text">Click if this solves your question</span>
                                        <a href="{% url 'questions:solve' answer.id %}"><span class="fa fa-check-circle-o"></span></a>
                                    {% elif question.solved and answer.solution == True %}
                                        <span class="fa fa-check-circle-o" style="color: #9aca27"></span></a>
                                    {% endif %}
                                </div>

                                {% if request.user in answer.voters %}
                                    <span class="vote_controls"><span class="fa fa-arrow-circle-o-up" style="opacity: .2"></span>
                                        <b>{{ answer.vote_counter }}</b>
                                        <span class="fa fa-arrow-circle-o-down" style="opacity: .2"></span>
                                    </span>
                                {% else %}
                                    <span class="vote_controls"><a href="{% url 'questions:voteup' answer.id %}"><span class="fa fa-arrow-circle-o-up"></span></a>
                                        <b>{{ answer.vote_counter }}</b>
                                        <a href="{% url 'questions:votedown' answer.id %}"><span class="fa fa-arrow-circle-o-down"></span></a>
                                    </span>
                                {% endif %}

                                <span>by <a href="{% url 'questions:profile' answer.user.id %}">{{ answer.user }}</a>
                                    | posted {{ answer.created }} </span>
                            </div>

                                <div class="answer_body"><i>{{ answer.body|safe }}</i></div>

                                <div class="answer_actions">
                                    {% if request.user in answer.flaggers %}
                                        <span class="fa fa-flag btn btn-link disabled"></span><span class="badge badge-pill badge-info">{{ answer.flag_set.all.count }}</span>
                                    {% else %}
                                        <button id="{{ answer.id }}" value="a" type="button" class="flag btn btn-link" data-toggle="modal" data-target="#exampleModalLong">
                                            <span class="fa fa-flag-o"></span>
                                        </button>
                                    {% endif %}

                                </div>

                            </li>
                    {% endfor %}
                </ul>

            {% endif %}

        </div>

        <div class="col-lg-3">

            {% if related.count > 0 %}

                <h5>RELATED QUESTIONS</h5>
                <ul>
                    {% for question in related %}
                        <a href="{% url 'questions:question_detail' question.id %}"><li>{{ question }}</li></a>
                    {% endfor %}
                </ul>

            {% endif %}
        </div>

    </div>
    <hr >
    <div class="row">
        <div class="col-lg-8">
            {% if request.user.is_authenticated %}
                <div id="answer_wrapper">
                    <h5>New Answer</h5>
                    <form action="{% url 'questions:post_answer' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" value="{{ question.id }}" name="question_id"/>
                        {{ form.media }}
                        {{ form.body }}
                        <br />
                        <br />
                        <p><button type="submit" class="btn btn-outline-info btn-lg">ANSWER</button> </p>
                    </form>
                </div>
            {% endif %}
        </div>
            {% if request.user.is_authenticated %}
                <div class="col-lg-4">
                    <i><h5>TIPS</h5>
                    <ul>
                        <li>Pay it forward</li>
                        <li>Answer the question specifically</li>
                        <li><a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">Provide context for links</a></li>
                        <li>Write to the best of your ability</li>
                        <li>Answer well-asked questions</li>
                        <li>Always be polite and have fun</li>
                    </ul></i>
                </div>
            {% endif %}

    </div>

</div>
<br />

<script>

    // FLAGS
    let flags = document.getElementsByClassName('flag');
    // console.log(flags);
    for (let i = 0; i < flags.length; ++i) {
        let id = flags[i].id;
        let type = flags[i].value;
        let button = document.getElementsByClassName('flag')[i];
        // console.log(button);
        button.onclick = function() {
            console.log(`id: ${id} - type ${type}`);
            let flag_type = document.getElementById('flag_type');
            let flag_type_id = document.getElementById('flag_type_id');
            flag_type.setAttribute('value', type);
            flag_type_id.setAttribute('value', id)
        };
    }

    // AJAX Question Bookmarks create/delete
    let bookmark = document.getElementById('question_bookmark');
    bookmark.onclick = function() {
        if (bookmark.className === 'fa fa-bookmark-o') {
            let id = {{ question.id }}
            let data = {'question_id': id};
            bookmark.className = 'fa fa-bookmark';
            http_post("{% url 'questions:new_bookmark' %}", data, function(response) {
                alert("Bookmark added");
            })
        } else {
            bookmark.className = 'fa fa-bookmark-o';
            let id = {{ question.id }}
            let data = {'question_id': id};
            http_post("{% url 'questions:delete_bookmark' %}", data, function(response) {
                alert("Bookmark deleted")
            })
        }
    };

    let flag = document.getElementById('question_flag');
    flag.onclick = function() {

    };


</script>

{% endblock %}

nwpp_prototypes/questions/templates/questions/tags.html
{% extends 'questions/base.html' %}

{% block heading %}

    <div class="row" id="heading">
        <div class="col">
            <span style="font-size: 2em" class="page_heading">TAGS</span>
        </div>
    </div>

{% endblock %}

{% block content %}

<br />
<div class="container">
    <ul>
        {% for category in categories %}
            <li>{{ category }}</li>
        {% endfor %}
    </ul>

    <ul>
        {% for tag in all_tags %}
            <li>{{ tag }}</li>
        {% endfor %}
    </ul>

</div>
<br />


{% endblock %}